const SHIZUKU_PRODUCTS = [
    { title: "Shizuku House Blend", title_jp: "雫ハウスブレンド", price: "12.99", img: "coffee1.png", desc: "White Peach, Jasmine, Honey", desc_jp: "白桃、ジャスミン、蜂蜜", tagline: "Our signature blend: smooth, floral, and lightly roasted.", tagline_jp: "当店のシグネチャーブレンド：なめらかでフローラル、浅煎り。", roast: "light", popular: 1 },
    { title: "Sakura Mid Roast", title_jp: "桜ミディアムロースト", price: "14.50", img: "coffee2.png", desc: "Almond, Milk Chocolate, Cherry", desc_jp: "アーモンド、ミルクチョコ、チェリー", tagline: "A balanced, nutty roast, perfect for your daily latte.", tagline_jp: "バランスの取れたナッツ風味のロースト。毎日のラテに最適。", roast: "medium", popular: 2 },
    { title: "Midnight Espresso", title_jp: "ミッドナイト・エスプレッソ", price: "15.99", img: "coffee3.png", desc: "Dark Cocoa, Molasses, Smoke", desc_jp: "ダークココア、糖蜜、スモーキー", tagline: "Rich, bold, and with a deep chocolatey finish.", tagline_jp: "濃厚でコクがあり、深いチョコレートの後味。", roast: "dark", popular: 6 },
    { title: "Vanilla Sakura Blend", title_jp: "バニラ桜ブレンド", price: "13.75", img: "coffee4.png", desc: "Creamy Vanilla, Cherry Blossom, Sweetness", desc_jp: "バニラ、桜、甘み", tagline: "Delicate vanilla infused with subtle sakura notes.", tagline_jp: "繊細なバニラとほのかな桜の香り。", roast: "flavored", popular: 23 },
    { title: "Morning Blossom", title_jp: "モーニングブロッサム", price: "13.00", img: "coffee5.png", desc: "Lemon Zest, Green Apple, Floral", desc_jp: "レモン、青リンゴ、フローラル", tagline: "Bright and citrusy, ideal for a slow morning.", tagline_jp: "明るくシトラス系。ゆったりとした朝に最適。", roast: "light", popular: 24 },
    { title: "Sakura Caramel Roast", title_jp: "桜キャラメルロースト", price: "13.20", img: "coffee6.png", desc: "Toffee, Floral, Brown Sugar", desc_jp: "トフィー、フローラル、黒糖", tagline: "Smooth caramel sweetness with delicate floral notes.", tagline_jp: "なめらかなキャラメルの甘さと繊細な花の香り。", roast: "medium", popular: 22 },
    { title: "Kyoto Night Roast", title_jp: "京都ナイトロースト", price: "16.00", img: "coffee7.png", desc: "Cedar, Tobacco, Dark Chocolate", desc_jp: "スギ、タバコ、ダークチョコ", tagline: "Deep, smoky, and bold, inspired by Kyoto's night cafés.", tagline_jp: "京都の夜カフェにインスパイアされた、深くスモーキーで大胆な味わい。", roast: "dark", popular: 7, },
    { title: "Strawberry Latte Blend", title_jp: "ストロベリーラテブレンド", price: "14.99", img: "coffee8.png", desc: "Fresh Strawberry, Cream, Candy", desc_jp: "完熟苺、生クリーム、キャンディ", tagline: "Creamy strawberry aroma with a soft, sweet finish.", tagline_jp: "クリーミーな苺の香りと優しい甘さ。", roast: "flavored", popular: 8 },
    { title: "Tokyo Drip Blend", title_jp: "東京ドリップブレンド", price: "12.80", img: "coffee9.png", desc: "Nutty, Clean, Sweet Citrus", desc_jp: "ナッツ、クリーン、甘い柑橘", tagline: "Clean, balanced, and ideal for pour-over brewing.", tagline_jp: "クリーンでバランスの取れた、ハンドドリップに最適なブレンド。", roast: "medium", popular: 9, },
    { title: "Samurai Espresso", title_jp: "侍エスプレッソ", price: "17.90", img: "coffee10.png", desc: "Blackberry, Cocoa Nib, Pepper", desc_jp: "ブラックベリー、ダークチョコ、キレ", tagline: "Intense, bold, with a sharp chocolate finish.", tagline_jp: "力強く大胆で、キレのあるチョコレートの後味。", roast: "dark", popular: 10 },
    { title: "Cherry Blossom Breeze", title_jp: "桜のそよ風", price: "10.99", img: "coffee11.png", desc: "Spring Water, Sakura Petal, Airy", desc_jp: "天然水、桜の花びら、軽やか", tagline: "Soft floral aroma with a gentle sweetness, like a spring breeze.", tagline_jp: "春のそよ風のような、柔らかな花の香りと穏やかな甘み。", roast: "light", popular: 11 },
    { title: "Honey Sakura Roast", title_jp: "ハニー桜ロースト", price: "15.00", img: "coffee12.png", desc: "Wild Honey, Floral, Velvety", desc_jp: "野生の蜂蜜、フローラル、ベルベットの質感", tagline: "Natural honey sweetness infused with delicate sakura aroma.", tagline_jp: "天然の蜂蜜の甘みと繊細な桜の香り。", roast: "flavored", popular: 12 },
    { title: "Osaka Café Blend", title_jp: "大阪カフェブレンド", price: "13.90", img: "coffee13.png", desc: "Hazelnut, Caramel, Warmth", desc_jp: "ヘーゼルナッツ、キャラメル、温かみ", tagline: "Nutty, warm, and cozy—a true café-style comfort.", tagline_jp: "ナッツのような温かみと心地よさ。カフェスタイルの快適さ。", roast: "medium", popular: 13, },
    { title: "Imperial Roast", title_jp: "インペリアルロースト", price: "25.00", img: "coffee14.png", desc: "Full Body, Oak, Intense", desc_jp: "フルボディ、オーク、力強さ", tagline: "Strong, rich, and royal—for true dark roast connoisseurs.", tagline_jp: "力強く豊かで高貴。真の深煎り愛好家のために。", roast: "dark", popular: 14 },
    { title: "Matcha Latte Blend", title_jp: "抹茶ラテブレンド", price: "11.90", img: "coffee15.png", desc: "Matcha, Cream, Umami", desc_jp: "抹茶、クリーミー、旨味", tagline: "Light roast with creamy matcha undertones, a unique fusion.", tagline_jp: "クリーミーな抹茶のニュアンスを持つ浅煎り。ユニークな融合。", roast: "light", popular: 15 },
    { title: "Sakura Mocha Blend", title_jp: "桜モカブレンド", price: "14.00", img: "coffee16.png", desc: "Cocoa, Cherry Blossom, Sweet", desc_jp: "ココア、桜、甘い", tagline: "Chocolate and sakura create a dreamy, harmonious blend.", tagline_jp: "チョコレートと桜が織りなす、夢のようなハーモニー。", roast: "flavored", popular: 16 },
    { title: "Hokkaido Milk Blend", title_jp: "北海道ミルクブレンド", price: "13.50", img: "coffee17.png", desc: "Milk, Butter, Smoothness", desc_jp: "ミルク、バター、滑らかさ", tagline: "Extra creamy and smooth, reminiscent of Hokkaido's snowy landscapes.", tagline_jp: "北海道の雪景色を思わせる、非常にクリーミーでなめらかな味わい。", roast: "medium", popular: 17, },
    { title: "Uji Matcha Espresso", title_jp: "宇治抹茶エスプレッソ", price: "17.00", img: "coffee18.png", desc: "Earthy Matcha, Bold, Fusion", desc_jp: "大地の抹茶、ボールド、融合", tagline: "A harmonious fusion of dark roast and premium Uji matcha.", tagline_jp: "深煎りと高級宇治抹茶の調和。", roast: "flavored", popular: 18, },
    { title: "Golden Hour Roast", title_jp: "ゴールデンアワーロースト", price: "11.00", img: "coffee19.png", desc: "Apricot, Honey, Sunshine", desc_jp: "アプリコット、蜂蜜、サンシャイン", tagline: "Bright and sun-kissed with hints of apricot and honey.", tagline_jp: "アプリコットと蜂蜜が香る、明るく太陽のような味わい。", roast: "light", popular: 19 },
    { title: "Zen Garden Decaf", title_jp: "禅ガーデン・デカフェ", price: "19.99", img: "coffee20.png", desc: "Herbal, Peace, Clean", desc_jp: "ハーブ、静寂、クリーン", tagline: "Calm and peaceful flavors, without the caffeine kick.", tagline_jp: "カフェインなしで楽しむ、穏やかで落ち着いた味わい。", roast: "dark", popular: 20 },
    { title: "Sakura Citrus Blend", title_jp: "桜シトラスブレンド", price: "16.50", img: "coffee21.png", desc: "Orange, Sakura, Refreshing", desc_jp: "オレンジ、桜、爽やか", tagline: "A refreshing blend with bright citrus notes and a hint of sakura.", tagline_jp: "明るいシトラスノートと桜の香りが爽やかなブレンド。", roast: "light", popular: 21 },
    { title: "Obsidian Velvet Roast", title_jp: "黒曜石ベルベットロースト", price: "65.00", img: "coffee22.png", desc: "Mineral, Volcanic, Smooth", desc_jp: "ミネラル、火山、滑らか", tagline: "Filtered through volcanic glass for an exceptionally smooth finish.", tagline_jp: "火山ガラスでろ過した、驚くほどなめらかな仕上がり。", roast: "dark", popular: 3 },
    { title: "Dragon Pearl Jasmine", title_jp: "ドラゴンパール・ジャスミン", price: "80.00", img: "coffee23.png", desc: "Jasmine, Floral, Heavy Body", desc_jp: "ジャスミン、フローラル、重厚", tagline: "Co-fermented with hand-rolled jasmine pearls for intoxicating floral notes.", tagline_jp: "手巻きジャスミンパールと共に発酵させた、魅惑的な花の香り。", roast: "light", popular: 4 },
    { title: "Kuro-Diamond Roast", title_jp: "黒ダイヤモンドロースト", price: "75.00", img: "coffee24.png", desc: "Crisp, Mineral, Obsidian", desc_jp: "クリスプ、ミネラル、黒曜石", tagline: "Filtered through volcanic obsidian glass for an impossibly crisp finish.", tagline_jp: "火山性黒曜石ガラスでろ過した、驚くほどクリスプな仕上がり。", roast: "flavored", popular: 5 },
    { title: "Yuzu Mist Roast", title_jp: "柚子ミストロースト", price: "15.99", img: "coffee25.png", desc: "Yuzu, Citrus, Mist", desc_jp: "柚子、シトラス、霧", tagline: "Bright citrus notes meet a delicate misty finish.", tagline_jp: "爽やかな柑橘の香りと、繊細でミスティな後味。", roast: "light", popular: 25 },
    { title: "Herbal Lantern Blend", title_jp: "ハーバル・ランタン・ブレンド", price: "13.90", img: "coffee26.png", desc: "Herb, Aromatic, Soothing", desc_jp: "ハーブ、アロマ、安らぎ", tagline: "A soothing medium roast with aromatic herbal notes and a smooth finish.", tagline_jp: "芳醇なハーブの香りが心地よい、安らぎの中煎りブレンド。", roast: "medium", popular: 26 },
    { title: "Sage Mist Blend", title_jp: "セージミスト・ブレンド", price: "19.90", img: "coffee27.png", desc: "Sage, Earthy, Velvety", desc_jp: "セージ、アース、ベルベット", tagline: "Grounding earthy notes with a sophisticated velvety finish.", tagline_jp: "大地の香りと洗練されたなめらかな後味。", roast: "medium", popular: 27 },
    { title: "Vanilla Anmitsu Roast", title_jp: "バニラあんみつロースト", price: "49.00", img: "coffee28.png", desc: "Vanilla, Red Bean, Sweetness", desc_jp: "バニラ, 小豆, 甘み", tagline: "A creamy dessert-like roast inspired by traditional Japanese sweets.", tagline_jp: "和菓子にインスパイアされた、クリーミーでデザートのような一杯。", roast: "medium", popular: 28 },
    { title: "Sakura Latte Charm Keychain", title_jp: "桜ラテ・チャームキーホルダー", price: "4.90", img: "keychain.png", desc: "Miniature, Hand-painted, Collectible", desc_jp: "ミニチュア, 手書き, コレクション", tagline: "A miniature sakura latte charm to carry the spirit of Shizuku everywhere.", tagline_jp: "どこへでも雫の精神を持ち歩ける、ミニチュアの桜ラテチャーム。", roast: "accessory", popular: 29, material: "Enamel, Zinc Alloy", material_jp: "エナメル、亜鉛合金", dimensions: "3.5cm x 2.5cm", dimensions_jp: "3.5cm x 2.5cm" },
    { title: "Shizuku Serenity Charm Keychain", title_jp: "雫・静心お守りキーホルダー", price: "4.90", img: "keychain2.png", desc: "Omamori-style, Embroidered, Tranquil", desc_jp: "お守り風, 刺繍, 平穏", tagline: "A refined omamori-style charm featuring the kanji for 'calm heart' (静心).", tagline_jp: "「静心」の文字を刺繍した、心を落ち着かせる洗練されたお守り風チャーム。", roast: "accessory", popular: 30, material: "Woven Fabric, Gold Thread", material_jp: "織物、金糸", dimensions: "4.0cm x 6.0cm", dimensions_jp: "4.0cm x 6.0cm" },
    { title: "Imperial Blends Pin Set", title_jp: "インペリアル・ブレンド ピンバッジセット", price: "5.99", img: "pins1.png", desc: "Enamel, Gold-plated, Collectible", desc_jp: "エナメル, 金メッキ, コレクション", tagline: "A refined enamel pin collection inspired by the harmony of tea and coffee rituals. Features a lotus blossom, milk bottle, divided cup, and crescent moon.", tagline_jp: "お茶とコーヒーの調和にインスパイアされた、洗練されたエナメルピンのコレクション。蓮の花、ミルクボトル、抹茶とエスプレッソの分割カップ、三日月をモチーフにしています。", roast: "accessory", popular: 31, material: "Enamel, Gold-plated Zinc Alloy", material_jp: "エナメル、金メッキ亜鉛合金", dimensions: "1.5cm - 2.5cm each", dimensions_jp: "各 1.5cm - 2.5cm" },
    { title: "Tranquil Blends Pin Set", title_jp: "トランキル・ブレンド ピンバッジセット", price: "5.99", img: "pins2.png", desc: "Zen Ripple, Sakura Essence, Citrus Mist, Strawberry Latte", desc_jp: "禅の波紋、桜のエッセンス、シトラスの霧、ストロベリーラテ", tagline: "A soothing enamel pin collection inspired by serene moments. Each gold-framed piece features soft gradients capturing the essence of mindfulness and cafe charm.", tagline_jp: "穏やかなひとときとカフェの魅力にインスパイアされた、心安らぐエナメルピンコレクション。柔らかなグラデーションとゴールドの縁取りが、日々に静寂と彩りを与えます。", roast: "accessory", popular: 32, material: "Enamel, Gold-plated Zinc Alloy", material_jp: "エナメル、金メッキ亜鉛合金", dimensions: "Approx. 2.5cm each", dimensions_jp: "各約2.5cm" },
    { title: "Gift Card ¥1,000", title_jp: "ギフトカード ¥1,000", price: "6.99", priceDigital: "6.29", img: "giftcard1000.png", desc: "Gift card - ¥1,000 value", desc_jp: "ギフトカード - ¥1,000分", tagline: "Perfect gift for coffee lovers", tagline_jp: "コーヒー愛好家に最適なギフト", roast: "giftcard", giftValue: 1000, digitalDiscount: 0.10 },
    { title: "Gift Card ¥2,500", title_jp: "ギフトカード ¥2,500", price: "17.50", priceDigital: "15.75", img: "giftcard2500.png", desc: "Gift card - ¥2,500 value", desc_jp: "ギフトカード - ¥2,500分", tagline: "Perfect gift for coffee lovers", tagline_jp: "コーヒー愛好家に最適なギフト", roast: "giftcard", giftValue: 2500, digitalDiscount: 0.10 },
    { title: "Gift Card ¥5,000", title_jp: "ギフトカード ¥5,000", price: "35.00", priceDigital: "31.50", img: "giftcard5000.png", desc: "Gift card - ¥5,000 value", desc_jp: "ギフトカード - ¥5,000分", tagline: "Perfect gift for coffee lovers", tagline_jp: "コーヒー愛好家に最適なギフト", roast: "giftcard", giftValue: 5000, digitalDiscount: 0.10 },
    { title: "Gift Card ¥20,000", title_jp: "ギフトカード ¥20,000", price: "109.00", priceDigital: "98.10", img: "giftcard20000.png", desc: "Gift card - ¥20,000 value", desc_jp: "ギフトカード - ¥20,000分", tagline: "Perfect gift for coffee lovers", tagline_jp: "コーヒー愛好家に最適なギフト", roast: "giftcard", giftValue: 20000, digitalDiscount: 0.10 }
];

function formatPrice(eur) {
    const lang = localStorage.getItem("language") || "en";
    const exchangeRate = 160;
    const priceVal = parseFloat(eur) || 0;
    if (lang === 'jp') return '¥' + Math.round(priceVal * exchangeRate).toLocaleString();
    return '€' + priceVal.toFixed(2);
}

function getSimulatedStatus(timestamp) {
    const diffMin = (Date.now() - timestamp) / 60000;
    if (diffMin > (3 * 24 * 60)) return "Delivered";
    if (diffMin > (1 * 24 * 60)) return "Shipped";
    if (diffMin > 60) return "Preparing";
    if (diffMin > 0) return "Payment Confirmed";
    return "Paid & Preparing";
}
